# ここから

In [48]:
import pandas as pd
# エクセルファイルの シート名 import から読み出す
data = pd.read_excel("aoutogen_importdata2.xlsx", sheet_name='import', index_col=None)
# 5行目までを取り出す
data_index = data[0:4]
# 5行目までを dropする
data_body = data.drop([0,1,2,3])
# data_indexの2行目をカラム名に設定
columnsname = data_index.loc[0].values.tolist()
data_body.columns = columnsname
# index を振りなおす
data_body['parent'] = data_body['parent'].astype(str)
data_body['children'] = data_body['children'].astype(str)
# data_body.reset_index(inplace=True, drop=True)
# data_body2 = data_body.set_index('parent', drop=False)
# data_body2 = data_body.set_index('parent'+'children', drop=False)
data_body2 = data_body.assign(index=lambda x: x.parent.str.cat(x.children.str.zfill(4))).set_index('index')
data_body2

,parent,children,#.id,.uri,.metadata.path[0],.pos_index[0],.publish_status,.feedback_mail[0],.cnri,.doi_ra,...,.metadata.item_9_relation_40[0].subitem_relation_type,.metadata.item_9_relation_40[0].subitem_relation_type_id.subitem_relation_type_id_text,.metadata.item_9_relation_40[0].subitem_relation_type_id.subitem_relation_type_select,.metadata.item_9_relation_41[0].subitem_relation_name[0].subitem_relation_name_language,.metadata.item_9_relation_41[0].subitem_relation_name[0].subitem_relation_name_text,.metadata.item_9_relation_41[0].subitem_relation_type,.metadata.item_9_relation_41[0].subitem_relation_type_id.subitem_relation_type_id_text,.metadata.item_9_relation_41[0].subitem_relation_type_id.subitem_relation_type_select,.metadata.item_9_identifier_60[0].subitem_identifier_type,.metadata.item_9_identifier_60[0].subitem_identifier_uri
index,,,,,,,,,,,,,,,,,,,,,
00000,0,0,2001301,https://jc-test2.repo.nii.ac.jp/records/2001301,2057,New Node For English,public,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00001,0,1,NaN,NaN,746,A100a Journal Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00002,0,2,NaN,NaN,747,Journal Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00003,0,3,NaN,NaN,2321,IVY,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00004,0,4,NaN,NaN,1547,NAGOYA STUDIES IN INDIAN CULTURE AND BUDDHISM ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00005,0,5,NaN,NaN,790,Language and Culture Research Series,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00006,0,6,NaN,NaN,803,Issues in Language and Culture,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00007,0,7,NaN,NaN,2606,Nagoya University Journal of Japanese Language...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00008,0,8,NaN,NaN,1432,Journal of Chinese language and literature,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00009,0,9,NaN,NaN,522,"The Journal of the Faculty of Letters, Nagoya ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00010,0,10,NaN,NaN,798,Studies in media and culture,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00011,0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00012,0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000,1,0,2001301,https://jc-test2.repo.nii.ac.jp/records/2001301,2057,New Node For English,public,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10001,1,1,NaN,NaN,746,A100a Journal Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# A value is trying to be set on a copy of a slice from a DataFrame
# data_body3 = data_body2.copy()
# data_body4 = data_body3[data_body3['children'] == '0'].fillna('--KESSON--', inplace=True).copy()
data_body3 = data_body2[data_body2['children'] == '0'].copy()
data_body3.fillna('--KESSON--', inplace=True)

In [61]:
data_body2.update(data_body3)

In [62]:
data_body2

,parent,children,#.id,.uri,.metadata.path[0],.pos_index[0],.publish_status,.feedback_mail[0],.cnri,.doi_ra,...,.metadata.item_9_relation_40[0].subitem_relation_type,.metadata.item_9_relation_40[0].subitem_relation_type_id.subitem_relation_type_id_text,.metadata.item_9_relation_40[0].subitem_relation_type_id.subitem_relation_type_select,.metadata.item_9_relation_41[0].subitem_relation_name[0].subitem_relation_name_language,.metadata.item_9_relation_41[0].subitem_relation_name[0].subitem_relation_name_text,.metadata.item_9_relation_41[0].subitem_relation_type,.metadata.item_9_relation_41[0].subitem_relation_type_id.subitem_relation_type_id_text,.metadata.item_9_relation_41[0].subitem_relation_type_id.subitem_relation_type_select,.metadata.item_9_identifier_60[0].subitem_identifier_type,.metadata.item_9_identifier_60[0].subitem_identifier_uri
index,,,,,,,,,,,,,,,,,,,,,
00000,0,0,2001301.0,https://jc-test2.repo.nii.ac.jp/records/2001301,2057.0,New Node For English,public,--KESSON--,--KESSON--,--KESSON--,...,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--
00001,0,1,NaN,NaN,746,A100a Journal Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00002,0,2,NaN,NaN,747,Journal Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00003,0,3,NaN,NaN,2321,IVY,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00004,0,4,NaN,NaN,1547,NAGOYA STUDIES IN INDIAN CULTURE AND BUDDHISM ...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00005,0,5,NaN,NaN,790,Language and Culture Research Series,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00006,0,6,NaN,NaN,803,Issues in Language and Culture,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00007,0,7,NaN,NaN,2606,Nagoya University Journal of Japanese Language...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00008,0,8,NaN,NaN,1432,Journal of Chinese language and literature,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00009,0,9,NaN,NaN,522,"The Journal of the Faculty of Letters, Nagoya ...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00010,0,10,NaN,NaN,798,Studies in media and culture,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00011,0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00012,0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000,1,0,2001301.0,https://jc-test2.repo.nii.ac.jp/records/2001301,2057.0,New Node For English,public,--KESSON--,--KESSON--,--KESSON--,...,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--,--KESSON--
10001,1,1,NaN,NaN,746,A100a Journal Article,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# tatemochi_df = data_body2.stack().reset_index()
# tatemochi_df = data_body2.melt(id_vars='children', var_name='項目', value_name='値')
# melt 残す変数（id_vars ）と melt し縦持ちにする変数（values_vars）を指定
tatemochi_df = data_body2.melt(id_vars=["children", "parent"])
tatemochi_df
tatemochi_df2 = tatemochi_df.dropna(subset=['value'])
tatemochi_df2

,children,parent,variable,value
0,0,0,#.id,2001301
13,0,1,#.id,2001301
15,0,0,.uri,https://jc-test2.repo.nii.ac.jp/records/2001301
28,0,1,.uri,https://jc-test2.repo.nii.ac.jp/records/2001301
30,0,0,.metadata.path[0],2057
...,...,...,...,...
1138,0,1,.metadata.item_language[0].subitem_language,jpn
1140,0,0,.metadata.item_resource_type.resourcetype,departmental bulletin paper
1153,0,1,.metadata.item_resource_type.resourcetype,departmental bulletin paper
1155,0,0,.metadata.item_resource_type.resourceuri,http://purl.org/coar/resource_type/c_6501
1168,0,1,.metadata.item_resource_type.resourceuri,http://purl.org/coar/resource_type/c_6501

In [37]:
# 項目の[0]をchildrenの[x]で置換して、new_column 列を作成
# tatemochi_df2->tatemochi_df 2に戻す
tatemochi_df2["項目2"] = tatemochi_df2.apply(
    lambda x: x.variable.replace('[0]', '[' + str(x.children) + ']', 1), axis=1)
# tatemochi_df3 = tatemochi_df2.set_index('children')
# tatemochi_df4 = tatemochi_df3.drop(['項目'], axis=1)
tatemochi_df2

<ipython-input-37-43466514a022>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tatemochi_df2["項目2"] = tatemochi_df2.apply(

,children,parent,variable,value,項目2
0,0,0,#.id,2001301,#.id
13,0,1,#.id,2001301,#.id
15,0,0,.uri,https://jc-test2.repo.nii.ac.jp/records/2001301,.uri
28,0,1,.uri,https://jc-test2.repo.nii.ac.jp/records/2001301,.uri
30,0,0,.metadata.path[0],2057,.metadata.path[0]
...,...,...,...,...,...
1138,0,1,.metadata.item_language[0].subitem_language,jpn,.metadata.item_language[0].subitem_language
1140,0,0,.metadata.item_resource_type.resourcetype,departmental bulletin paper,.metadata.item_resource_type.resourcetype
1153,0,1,.metadata.item_resource_type.resourcetype,departmental bulletin paper,.metadata.item_resource_type.resourcetype
1155,0,0,.metadata.item_resource_type.resourceuri,http://purl.org/coar/resource_type/c_6501,.metadata.item_resource_type.resourceuri
1168,0,1,.metadata.item_resource_type.resourceuri,http://purl.org/coar/resource_type/c_6501,.metadata.item_resource_type.resourceuri

In [ ]:
# print(tatemochi_df2)
tatemochi_df2.to_csv("tatemochi_df2.csv")

In [ ]:
# ためしにただの転置をしてみる
data_body_T = tatemochi_df.T
data_body_T

In [ ]:
# 縦持ちを横持ちに戻す
data_body4 = tatemochi_df2.pivot(index='parent', columns='項目2', values='value')
# print(data_body4.dropna(how='all'))
data_body4

# ValueError: Index contains duplicate entries, cannot reshape
# ラベル同士の組み合わせで被りがあるとエラーが返ってきます。
# tatemochi_df2 = tatemochi_df.dropna(subset=['value'])　をしないと・・・

In [ ]:
data_index

In [ ]:
data_body4_list = list(data_body4.columns)

In [ ]:
original_index = data_index.copy(deep=True)  # = だと参照渡しになる
original_index.columns = data_index.loc[0, :].to_list()
original_index.drop(original_index.index[[0,1,2,3]], inplace=True)
# data_body4のカラム名との重複排除
# print(list(original_index.columns))
# print(data_body4_list)
# original_index.columns
# new_list = set(list(original_index.columns) + data_body4_list) # 単に重複排除
new_list = list(set(list(original_index.columns)) - set(data_body4_list)) # 差分
# new_list_df = pd.DataFrame( new_list )
print(new_list)
'''
new_list_df = new_list_df.set_index(0)  # 列をインデックス（行名）に割り当てるset_index
# リストを転置　.T
pv_new_list_df = new_list_df.T
#pv_new_list_df = new_list_df.pivot_table(
#    values=[0], index=[0], columns=[0])
pv_new_list_df
# original_index
# data_index.loc[0,:]
# data_body4.to_excel('./data_body4.xlsx', index=False,sheet_name='new_sheet_name')
'''

In [ ]:
# data_body4 = pd.concat([data_body4, original_index], axis=1, join="outer")
data_body4 = pd.concat([data_body4, pv_new_list_df], axis=1, join="outer")
# data_body4.merge(original_index, how="right")
data_body4
'''
data_body4 = pd.concat(
    [data_body4, data_index.loc[0, :]], axis=1, join="outer")
data_body4
'''

In [ ]:
data_body4

In [ ]:

# CSV(エクセル)に出力
data_body4.to_excel('./pandas_to_excel.xlsx', index=False,sheet_name='new_sheet_name')
data_body4.to_csv('./pandas_to_excel.csv', index=False, quotechar='"')

In [ ]:
data_index

In [ ]:
# #ItemType,紀要論文___Departmental_Bulletin_Paper(9) を文字列に出力する
# list を join して文字列にする
# print(data_index.values.tolist()) 
print(data_index.columns.values[2:5]) 
first_line = ','.join(data_index.columns.values[2:5])
print(first_line)

In [ ]:
# csvファイルを読みだして、文字列を先頭に追記
with open("pandas_to_excel.csv", "r", encoding="utf-8") as f:
    original_data = f.read()
with open("pandas_to_excel.csv", "w", encoding="utf-8") as f:
    f.write(first_line + '\n')
    f.write(original_data)

In [ ]:
print(data_index.loc[0,:])
'''
column_addRow = ','.join(addRow.loc[1, :].values)
print(column_addRow)
with open("column_addRow.csv", "w", encoding="utf-8") as f:
    f.write(column_addRow)
'''
'''
column_data_index = ','.join(data_index.loc[0, :].values)
# print(column_data_index)
with open("column_data_index.csv", "w", encoding="utf-8") as f:
    f.write(column_data_index)
'''    
'''
columns_data_body5 = ','.join(data_body5.columns.values)
with open("columns_data_body5.csv", "w", encoding="utf-8") as f:
    f.write(columns_data_body5)
'''

In [ ]:
# もしかしたらこれいらない？？？？
# 冒頭で外した data_index から、'Unnamed:'　が付いているカラムを外す
# data_index.columns.values
firstline = data_index.columns.tolist()
firstline = [col for col in firstline if not col.startswith('Unnamed:')]
# .T インデックスと列を転置 transpose
addRow = pd.DataFrame(firstline).T
# print(list(addRow.columns.values))
# addRow = [col for col in addRow if not col.startswith('Unnamed:')]
# addRow
# data_body4 = data_body4.append(addRow)

# drop している項目名も必要

In [ ]:
# 使わない？？
# xlsxファイルを読み込んで、"" で括ったTSVファイルに吐き出す
import pandas as pd
# read_file = pd.read_excel(r"C:\Users\user\test\sales-management-table.xlsx")
read_file = pd.read_excel(r"pandas_to_excel.xlsx")
read_file.to_csv(
    r"data3\data\紀要論文  Departmental Bulletin Paper(9).tsv", index=False, quoting=1, sep='\t')  # ,  header=True, index=None

In [ ]:
# xlsxファイルを読み込んで、"" で括ったTSVファイルに吐き出す
import pandas as pd
# read_file = pd.read_excel(r"C:\Users\user\test\sales-management-table.xlsx")
read_file = pd.read_excel(r"importdata.xlsx")
read_file.to_csv(
    r"data\data\紀要論文  Departmental Bulletin Paper(9).tsv", quoting=1, sep='\t', index=None, header=True)

In [ ]:
# data フォルダにある data フォルダをzipアーカイブする
import shutil
import sys

# C:\Users\libso23-user\OneDrive - The University of Tokyo\ドキュメント\JPCOAR\JPCOARTEST\アイテムインポートテスト\data\data
try:
    shutil.make_archive('import', format='zip', root_dir='data')
except Exception as e:
    print(e, file=sys.stderr)

In [ ]:
# カラム名に連番を振ってみる
# add numeric prefix to pandas dataframe column names
# 1_colA  2_colB
df.columns = [f'{i}_{x}' for i, x in enumerate(df.columns, 1)]